# Generated by Django 3.2.18 on 2023-03-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
